name: hchess
version: '0.1.0.0'
category: App
author: Sjur Millidahl
maintainer: sjur.millidahl@gmail.com
copyright: 2017 Sjur Millidahl
license: BSD3
github: githubuser/hchess
extra-source-files:
- README.md

dependencies:
  - record-dot-preprocessor
  - record-hasfield

default-extensions:
- BlockArguments
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DerivingVia
- GeneralisedNewtypeDeriving
- LambdaCase
- OverloadedStrings
- QuasiQuotes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators

ghc-options:
- -O2
- -fwarn-incomplete-patterns
- -fwarn-redundant-constraints
- -fwarn-unused-imports
- -fwarn-unused-packages
- -F -pgmF=record-dot-preprocessor

_exe-ghc-options: &exe-ghc-options
- -threaded
- -rtsopts
- '"-with-rtsopts=-N2 -T"'


library:
  source-dirs: src
  exposed-modules:
  - Chess
  - Printer
  - Evaluation
  - Move
  - AI
  - Position
  - Tree
  - GameLoop
  dependencies:
  - base >=4.7 && <5
  - bytestring
  - containers
  - deepseq
  - regex-tdfa
  - parallel
  - record-dot-preprocessor
  - transformers
  - utf8-string

executables:

  hchess:
    main: Main.hs
    source-dirs: app
    ghc-options: *exe-ghc-options
    dependencies:
    - base
    - hchess
    - deepseq

  hchess-profiled:
    main: Main.hs
    source-dirs: performance
    ghc-options: *exe-ghc-options
    dependencies:
    - base
    - hchess

tests:
  hchess-test:
    main: Main.hs
    source-dirs: test
    dependencies:
    - base
    - QuickCheck
    - hspec
    - containers
    - hchess

benchmarks:
  hchess-bench:
    main: Main.hs
    source-dirs: bench
    ghc-options: *exe-ghc-options
    dependencies:
    - base
    - hchess
    - criterion
