resolver: lts-13.1

packages:
- .

extra-deps:
- gtk-0.14.10
- gtk-mac-integration-0.3.4.0

flags: {}

extra-package-dbs: []

ghc-options:
    # All packages
    "$locals": -eventlog -O2
    "$targets": -Werror
